# Default values for influxdb-athena-crawler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

defaults:
  # -- The AWS region.
  region: ""

  # -- The AWS bucket to watch.
  bucket: ""

  # -- The bucket prefix.
  prefix: ""

  # -- The bucket files suffix.
  suffix: ""

  # -- The bucket processed flags suffix.
  processedFlagSuffix: ""

  # -- Whether to delete S3 objects after processing them.
  cleanObjects: false

  # -- After how long to delete the objects.
  maxObjectAge: 5m

  # -- If specified, always retain this number of most recent folders
  retainWindows: ""

  # -- The timestamp layout used in folder naming used for the retainWindows flag.
  storageTimestampLayout: ""

  # -- The global timeout.
  timeout: 10m

  # -- The InfluxDB servers addresses.
  influxServers: []

  # -- The InfluxDB token.
  influxToken: ""

  # -- The InfluxDB org to write to.
  influxOrg: ""

  # -- The InfluxDB bucket write to.
  influxBucket: ""

  # -- The InfluxDB bucket measurement.
  measurement: ""

  # -- The timestamp row in CSV.
  timestampRow: "timestamp"

  # -- The layout to parse timestamp.
  timestampLayout: "2006-01-02 15:04:05.000Z"

  # -- Tags to add to InfluxDB point. Could be of the form --tag=foo if tag name matches CSV row or --tag='foo={row:bar}' to specify row.
  tags: []

  # -- Fields to add to InfluxDB point. Could be of the form --field='foo={type:int,row:bar}', if not specified, CSV row matches field name. Type can be float, int, string or bool.
  fields: []

  # -- A reference to a secret wit AWS credentials (must contain awsKeyId / awsSecretKey).
  awsCredsSecret: "aws-creds"

  # -- The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
  schedule: "0 0 * * *"

  # -- Specifies the number of retries before marking a job as failed.
  backoffLimit: 6

  # -- The number of successful finished jobs to retain.
  successfulJobsHistoryLimit: 3

  # -- The number of failed finished jobs to retain.
  failedJobsHistoryLimit: 1

  # -- This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.
  suspend: false

  image:
    # -- influxdb-athena-crawler image repository.
    repository: eu.gcr.io/quortex-registry-public/influxdb-athena-crawler
    # -- influxdb-athena-crawler image tag (defaults to app version).
    tag: ""
    # -- influxdb-athena-crawler image pull policy.
    pullPolicy: IfNotPresent

  # -- influxdb-athena-crawler restartPolicy (supported values: "OnFailure", "Never").
  restartPolicy: OnFailure

  # -- A list of secrets used to pull containers images.
  imagePullSecrets: []

  # -- Helm's name computing override.
  nameOverride: ""

  # -- Helm's fullname computing override.
  fullnameOverride: ""

  # -- influxdb-athena-crawler container required resources.
  resources: {}

  # -- golang memory limit added to pods as an env var
  goMemLimit: ""

  # -- Max number of parallel routines to be used for object processing
  maxRoutines: ""

  # -- Annotations to be added to pods.
  podAnnotations: {}

  # -- Node labels for influxdb-athena-crawler pod assignment.
  nodeSelector: {}

  # -- Node tolerations for influxdb-athena-crawler scheduling to nodes with taints.
  tolerations: []

  # -- Affinity for influxdb-athena-crawler pod assignment.
  affinity: {}

# -- Crawlers map. Each of the elements of this map defines a crawler, merged with the default values
crawlers: {}

rbac:
  # -- Specifies whether rbac resources should be created.
  create: true
